### ISSUE TITLE
To wcale nie jest pseudorandomowe miejsce na tę notkę.

### ISSUE THREAD

**Issue by maks1823** [GLandStudio/NoteManagerG#1]
Zfollowuj mnie!

**Comment by maks1823** [comment]
@Gregory1234

**Comment by SamuraiNeo** [comment]
Maksiu, Maksiu 
Nazywasz się na Githubie prawdziwym imieniem i nazwiskiem, a mówisz o prywatności!
O co chodzi?

**Comment by maks1823** [comment]
@SamuraiNeo : Mylisz prywatność z anonimowością. Zobacz: np. Snowden ujawniając wyciek nie przyjął nicku, ujawniając podpisał się swoim imieniem i nazwiskiem, a jednak nazywany jest obrońcą prywatności. Za Wikipedią: 

> Prywatność (z łac. prīvātus "oddzielony") – **zdolność** jednostki lub grupy osób do utrzymania swych danych oraz osobistych zwyczajów i zachowań nieujawnionych publicznie.

No właśnie, zdolność. To o co nam chodzi, to o to, aby możliwość "utrzymania swych danych" nieujawnionych publicznie była zachowana i respektowana a nie bezprawnie i nielegalnie naruszana, a nasze prawa łamane bez naszej woli. Chodzi o zdolność, nie o przymus. Jeżeli chce się, można to ujawnić. Ponownie, chodzi o taką możliwość, wtedy i tylko wtedy gdy tego chcemy, jeśli nie- powinno być to respektowane.
**Nie jest.**

 Dla kontrastu definicja anonimowości, ponownie za Wikipedią:

> Anonimowość – **niemożność identyfikacji** tożsamości jednostki pośród innych członków danej społeczności, wprost w odniesieniu do osoby albo do pochodzącego od niej przedmiotu (utworu).

Widzisz różnice?










Rządy i tak pozbawiają nas i prywatności i anonimowości.


@Gregory1234  miałeś usunąć
